# Config for Text static fonts only
sources:
  - WixMadeforText-Regular.ufo
  - WixMadeforText-Medium.ufo
  - WixMadeforText-SemiBold.ufo
  - WixMadeforText-Bold.ufo
  - WixMadeforText-ExtraBold.ufo
  - WixMadeforText-Italic.ufo
  - WixMadeforText-MediumItalic.ufo
  - WixMadeforText-SemiBoldItalic.ufo
  - WixMadeforText-BoldItalic.ufo
  - WixMadeforText-ExtraBoldItalic.ufo
autohintTTF:
  false
buildVariable:
  false
buildWebfont:
  false
logLevel: WARNING
outputDir:
  '../fonts/Text'
vttSources:
  WixMadeforText-Bold.ttf:
    WixMadeforText-Bold_VTT_Hinting.ttx
  WixMadeforText-BoldItalic.ttf:
    WixMadeforText-BoldItalic_VTT_Hinting.ttx
  WixMadeforText-Italic.ttf:
    WixMadeforText-Italic_VTT_Hinting.ttx
  WixMadeforText-Medium.ttf:
    WixMadeforText-Medium_VTT_Hinting.ttx
  WixMadeforText-MediumItalic.ttf:
    WixMadeforText-MediumItalic_VTT_Hinting.ttx
  WixMadeforText-Regular.ttf:
    WixMadeforText-Regular_VTT_Hinting.ttx
  WixMadeforText-ExtraBold.ttf:
    WixMadeforText-ExtraBold_VTT_Hinting.ttx
  WixMadeforText-ExtraBoldItalic.ttf:
    WixMadeforText-ExtraBoldItalic_VTT_Hinting.ttx
googleFonts:
  true
category:
  - SANS_SERIF
