# Config for building Text and Display variable fonts only
sources:
  - WixMadeforDisplayVF_Wght.designspace
  - WixMadeforTextVF_Wght.designspace
  - WixMadeforTextItalicVF_Wght.designspace
autohintTTF:
  false
buildStatic:
  false
