# Config for Text static fonts only
sources:
  - WixMadeforText-Regular.ufo
  - WixMadeforText-Medium.ufo
  - WixMadeforText-SemiBold.ufo
  - WixMadeforText-Bold.ufo
  - WixMadeforText-ExtraBold.ufo
  - WixMadeforText-Italic.ufo
  - WixMadeforText-MediumItalic.ufo
  - WixMadeforText-SemiBoldItalic.ufo
  - WixMadeforText-BoldItalic.ufo
  - WixMadeforText-ExtraBoldItalic.ufo
autohintTTF:
  false
buildVariable:
  false
buildWebfont:
  false
logLevel: WARNING
outputDir:
  '../fonts/Text'
vttSources:
  WixMadeforText-Bold.ttf:
    vtt_data/WixMadeforText-Bold.ttx
  WixMadeforText-BoldItalic.ttf:
    vtt_data/WixMadeforText-BoldItalic.ttx
  WixMadeforText-Italic.ttf:
    vtt_data/WixMadeforText-Italic.ttx
  WixMadeforText-Medium.ttf:
    vtt_data/WixMadeforText-Medium.ttx
  WixMadeforText-MediumItalic.ttf:
    vtt_data/WixMadeforText-MediumItalic.ttx
  WixMadeforText-Regular.ttf:
    vtt_data/WixMadeforText-Regular.ttx
  WixMadeforText-ExtraBold.ttf:
    vtt_data/WixMadeforText-ExtraBold.ttx
  WixMadeforText-ExtraBoldItalic.ttf:
    vtt_data/WixMadeforText-ExtraBoldItalic.ttx
googleFonts:
  true
category:
  - SANS_SERIF
