# Config for Display static fonts only
sources:
  - WixMadeforDisplay-Regular.ufo
  - WixMadeforDisplay-Medium.ufo
  - WixMadeforDisplay-SemiBold.ufo
  - WixMadeforDisplay-Bold.ufo
  - WixMadeforDisplay-ExtraBold.ufo
logLevel: WARNING
autohintTTF:
  false
buildVariable:
  false
buildWebfont:
  false
outputDir:
  '../fonts/Display'
vttSources:
  WixMadeforDisplay-Bold.ttf:
    WixMadeforDisplay-Bold_VTT_Hinting.ttx
  WixMadeforDisplay-Regular.ttf:
    WixMadeforDisplay-Regular_VTT_Hinting.ttx
  WixMadeforDisplay-ExtraBold.ttf:
    WixMadeforDisplay-ExtraBold_VTT_Hinting.ttx
googleFonts:
  true
category:
  - SANS_SERIF
